Development
thepyrodancers/Calculator pull request #36
Opened 2020-05-21 21:25 UTC by awsumpter

Review and Merge

2020-05-21 21:30 UTC, davrdic commented on Calculator/Calculator.cpp
> +    Declaration (of variable)
fix diamond text

2020-05-21 21:31 UTC, davrdic commented on Calculator/Calculator.cpp
>      � Primary
fix symbol

2020-05-21 21:33 UTC, davrdic commented on Calculator/Functions.cpp
> +#include "conio.h"
remove unnecessary #includes

2020-05-21 21:40 UTC, davrdic commented on Calculator/Functions.cpp
> +    if (t.kind != ')') {
move all declarations to the top and put a space between declarations and algorithm

2020-05-21 21:43 UTC, davrdic commented on Calculator/Functions.cpp
> +    Token t2 = myts.get();
change myts to something that makes ya feel good

2020-05-21 21:46 UTC, davrdic commented on Calculator/Functions.cpp
> +
remove extra space

2020-05-21 21:58 UTC, davrdic commented on Calculator/Token_stream.cpp
> +    if(ch != print)
might can evaluate these in one line...if it evaluates print and fails, will it still evaluate the get. if it doesn't evaluate get and then does unget, we have a problem

2020-05-21 22:00 UTC, davrdic commented on Calculator/Token_stream.cpp
> +    if(ch != print)
maybe dont worry about it unless you really want to see what happens

2020-05-21 22:00 UTC, davrdic commented on Calculator/Token_stream.cpp
> +
love it

2020-05-21 22:04 UTC, davrdic requested changes
remove calculator.h and fix the other minor things

2020-05-25 23:10 UTC, pyronancy commented
hey hey

2020-05-25 23:12 UTC, pyronancy approved these changes
i did it

2020-05-25 23:13 UTC, pyronancy commented
is this it?

2020-05-25 23:14 UTC, davrdic approved these changes
is this doing it?

2020-05-25 23:14 UTC, merged